import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { isValidUrl, normalizeUrl } from "../utils/url.js";

/**
 * Placeholder audit data for v0.1.
 * Real crawling and rule-based analysis will be added in v0.2+.
 */
export interface AuditResult {
  tool: string;
  version: string;
  url: string;
  context: string;
  generatedAt: string;
  score: {
    overall: number;
    categories: {
      offerClarity: number;
      conversionReadiness: number;
      seoFoundation: number;
      contentOpportunity: number;
      adReadiness: number;
    };
  };
  findings: Array<{
    category: string;
    priority: string;
    title: string;
    description: string;
  }>;
  nextSteps: string[];
}

/**
 * Generate placeholder audit data.
 */
export function generatePlaceholderAudit(
  url: string,
  context: string,
): AuditResult {
  return {
    tool: "OpenGrowth",
    version: "0.1.0",
    url,
    context: context || "No business context provided.",
    generatedAt: new Date().toISOString(),
    score: {
      overall: 72,
      categories: {
        offerClarity: 70,
        conversionReadiness: 68,
        seoFoundation: 75,
        contentOpportunity: 80,
        adReadiness: 67,
      },
    },
    findings: [
      {
        category: "offer",
        priority: "high",
        title: "Clarify the above-the-fold value proposition",
        description:
          "Placeholder finding for v0.1. Real website analysis will be added in v0.2+.",
      },
      {
        category: "seo",
        priority: "medium",
        title: "Optimize meta description for click-through",
        description:
          "Placeholder finding for v0.1. Real SEO analysis will be added in v0.3+.",
      },
      {
        category: "content",
        priority: "medium",
        title: "Expand content depth around core product benefits",
        description:
          "Placeholder finding for v0.1. Content strategy generation will be added in v0.4+.",
      },
      {
        category: "conversion",
        priority: "high",
        title: "Add a clear primary call-to-action above the fold",
        description:
          "Placeholder finding for v0.1. Conversion analysis will be added in v0.3+.",
      },
      {
        category: "ads",
        priority: "low",
        title: "Surface ad-ready angles from existing page copy",
        description:
          "Placeholder finding for v0.1. Ad angle generation will be added in v0.5+.",
      },
    ],
    nextSteps: [
      "Add real crawler and parser in v0.2",
      "Add rule engine and scoring in v0.3",
      "Add content strategy generator in v0.4",
      "Add ad angle generator in v0.5",
      "Add HTML report output in v0.6",
    ],
  };
}

/**
 * Generate a Markdown report from audit data.
 */
export function generateMarkdownReport(audit: AuditResult): string {
  const lines: string[] = [];

  lines.push("# OpenGrowth Audit Report");
  lines.push("");
  lines.push("## Website");
  lines.push(`- **URL:** ${audit.url}`);
  lines.push("");
  lines.push("## Context");
  lines.push(audit.context);
  lines.push("");
  lines.push("## Growth Score");
  lines.push(`**Overall: ${audit.score.overall}/100**`);
  lines.push("");
  lines.push("## Category Scores");
  lines.push("");
  lines.push("| Category | Score |");
  lines.push("|----------|-------|");
  lines.push(`| Offer Clarity | ${audit.score.categories.offerClarity}/100 |`);
  lines.push(
    `| Conversion Readiness | ${audit.score.categories.conversionReadiness}/100 |`,
  );
  lines.push(
    `| SEO Foundation | ${audit.score.categories.seoFoundation}/100 |`,
  );
  lines.push(
    `| Content Opportunity | ${audit.score.categories.contentOpportunity}/100 |`,
  );
  lines.push(`| Ad Readiness | ${audit.score.categories.adReadiness}/100 |`);
  lines.push("");
  lines.push("## Key Findings");
  lines.push("");

  for (const finding of audit.findings) {
    const priorityIcon =
      finding.priority === "high"
        ? "🔴"
        : finding.priority === "medium"
          ? "🟡"
          : "🟢";
    lines.push(
      `### ${priorityIcon} [${finding.priority.toUpperCase()}] ${finding.title}`,
    );
    lines.push("");
    lines.push(`**Category:** ${finding.category}`);
    lines.push("");
    lines.push(finding.description);
    lines.push("");
  }

  lines.push("## Recommended Next Steps");
  lines.push("");
  for (let i = 0; i < audit.nextSteps.length; i++) {
    lines.push(`${i + 1}. ${audit.nextSteps[i]}`);
  }
  lines.push("");
  lines.push("## Version Notice");
  lines.push("");
  lines.push(
    "> This is a v0.1 placeholder audit. Real crawling, parsing, and rule-based analysis will be added in upcoming versions.",
  );
  lines.push("");
  lines.push(
    `*Generated by OpenGrowth v${audit.version} on ${audit.generatedAt}*`,
  );
  lines.push("");

  return lines.join("\n");
}

/**
 * Print a CLI-friendly audit summary to stdout.
 */
export function printAuditSummary(audit: AuditResult): void {
  console.log("");
  console.log("╔══════════════════════════════════════════════════════════╗");
  console.log("║              🚀 OpenGrowth Audit Report                 ║");
  console.log("╚══════════════════════════════════════════════════════════╝");
  console.log("");
  console.log(`  URL:      ${audit.url}`);
  console.log(`  Context:  ${audit.context}`);
  console.log(`  Date:     ${audit.generatedAt}`);
  console.log("");
  console.log("  ── Growth Score ──────────────────────────────────────");
  console.log(`  Overall:               ${audit.score.overall}/100`);
  console.log("");
  console.log("  ── Category Breakdown ────────────────────────────────");
  console.log(
    `  Offer Clarity:         ${audit.score.categories.offerClarity}/100`,
  );
  console.log(
    `  Conversion Readiness:  ${audit.score.categories.conversionReadiness}/100`,
  );
  console.log(
    `  SEO Foundation:        ${audit.score.categories.seoFoundation}/100`,
  );
  console.log(
    `  Content Opportunity:   ${audit.score.categories.contentOpportunity}/100`,
  );
  console.log(
    `  Ad Readiness:          ${audit.score.categories.adReadiness}/100`,
  );
  console.log("");
  console.log(
    `  ── Findings (${audit.findings.length}) ───────────────────────────────────`,
  );
  for (const finding of audit.findings) {
    const icon =
      finding.priority === "high"
        ? "🔴"
        : finding.priority === "medium"
          ? "🟡"
          : "🟢";
    console.log(`  ${icon} [${finding.priority.toUpperCase()}] ${finding.title}`);
  }
  console.log("");
  console.log(
    "  ⚠️  v0.1 placeholder — real analysis coming in v0.2+",
  );
  console.log("");
}

/**
 * Run the audit command.
 */
export function runAudit(options: {
  url: string;
  context: string;
  output: string;
  format: string;
}): void {
  // Validate URL
  if (!isValidUrl(options.url)) {
    console.error(`\n  ❌ Invalid URL: "${options.url}"`);
    console.error(
      '  Provide a valid URL like "https://example.com" or "example.com"\n',
    );
    process.exit(1);
  }

  const normalizedUrl = normalizeUrl(options.url);
  const audit = generatePlaceholderAudit(normalizedUrl, options.context);

  // Print summary to terminal
  printAuditSummary(audit);

  // Create output directory
  const outputDir = resolve(process.cwd(), options.output);
  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Write scorecard.json
  const scorecardPath = resolve(outputDir, "scorecard.json");
  writeFileSync(scorecardPath, JSON.stringify(audit, null, 2), "utf-8");

  // Write report.md
  const reportPath = resolve(outputDir, "report.md");
  const markdown = generateMarkdownReport(audit);
  writeFileSync(reportPath, markdown, "utf-8");

  console.log("  ── Output Files ─────────────────────────────────────");
  console.log(`  📄 ${scorecardPath}`);
  console.log(`  📄 ${reportPath}`);
  console.log("");
}
